root: ../../data
dataset: AmazonBeauty_550_Chron
maxlen: 100
maxlen4graph: 100
num_heads: 4
num_blocks: 1
hidden_size: 64
attn_dropout_rate: 0.5
hidden_dropout_rate: 0.2
epochs: 500
batch_size: 256
beta1: 0.9
beta2: 0.999
lr: 1.e-3
weight_decay: 1.e-1
pvn_weight: 0.005
distance_metric: wasserstein
optimizer: AdamWSEvo
L: 3
aggr: neumann
beta3: 0.99
H: 1