root: ../../data
dataset: MovieLens1M_550_Chron
maxlen: 200
maxlen4graph: 200
num_heads: 4
num_blocks: 1
hidden_size: 64
attn_dropout_rate: 0.2
hidden_dropout_rate: 0.1
epochs: 500
batch_size: 256
beta1: 0.9
beta2: 0.999
lr: 5.e-3
weight_decay: 1.e-1
pvn_weight: 0.001
distance_metric: wasserstein
optimizer: AdamWSEvo
L: 3
aggr: neumann
beta3: 0.99
H: 1