dataset: AmazonToys_550_Chron
root: ../../data
maxlen: 50
maxlen4graph: 50
epochs: 300
batch_size: 512
lr: 1.e-3
weight_decay: 1.e-1
embedding_dim: 64
hidden_size: 64
emb_dropout_rate: 0.4
num_gru_layers: 1
optimizer: AdamWSEvo
aggr: neumann
beta3: 0.99
L: 3
H: 1