root: ../../data
dataset: MovieLens1M_550_Chron
maxlen: 200
maxlen4graph: 10
num_heads: 4
num_blocks: 2
hidden_size: 64
dropout_rate: 0.1
mask_prob: 0.2
epochs: 500
batch_size: 256
beta1: 0.9
beta2: 0.999
lr: 1.e-3
weight_decay: 0.1
optimizer: AdamWSEvo
aggr: neumann
beta3: 0.99
L: 3
H: 1